/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JFrame;
import javax.swing.JPanel;


/**
 *
 * @author jramosal
 */
public class Interfaz extends javax.swing.JFrame {
    
    private Panel1 pnlPanel1;
    private Panel2 pnlPanel2;
    private Panel3 pnlPanel3;
    private Panel4 pnlPanel4;
    private Panel5 pnlPanel5;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);
        setSize(350,400);
        setTitle("Interfaz App");
        
        pnlPanel1=new Panel1("Panel1");
        pnlPanel1.setBounds(10,10,315,60);
        getContentPane().add(pnlPanel1);
        
        pnlPanel2=new Panel2("Panel2");
        pnlPanel2.setBounds(10,70,315,60);
        getContentPane().add(pnlPanel2);
        
        
        pnlPanel3=new Panel3("Panel3");
        pnlPanel3.setBounds(10,130,315,80);
        getContentPane().add(pnlPanel3);
        
        
        pnlPanel4=new Panel4("Panel4");
        pnlPanel4.setBounds(10,210,315,70);
        getContentPane().add(pnlPanel4);
        initComponents();
        
        pnlPanel5=new Panel5("Panel5",pnlPanel1,pnlPanel2,pnlPanel3,pnlPanel4);
        pnlPanel5.setBounds(10,280,315,60);
        getContentPane().add(pnlPanel5);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
