/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.border.TitledBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.AbstractBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JPanel;
/**
 *
 * @author jramosal
 */
public class Panel5 extends JPanel implements ActionListener {
    
    private JButton btnAceptar, btnCancelar;
    private Panel3 pnlPanel3;
    private Panel2 pnlPanel2;
    private Panel4 pnlPanel4;
    private Panel1 pnlPanel1;

    public Panel5(String title, Panel1 pnlPanel1, Panel2 pnlPanel2, Panel3 pnlPanel3, Panel4 pnlPanel4) {
        
        setBorder(new EmptyBorder(0,0,0,0));
        setBorder(new TitledBorder(title));
        
        JButton btnAceptar=new JButton("Aceptar");
        btnAceptar.setBounds(10,18,100,25);
        btnAceptar.addActionListener(this);
        add(btnAceptar);
        
        JButton btnCancelar=new JButton("Cancelar");
        btnCancelar.addActionListener(this);
        btnCancelar.setBounds(150,18,100,25);
        add(btnCancelar);
        initComponents();
        
        this.btnAceptar = btnAceptar;
        this.btnCancelar = btnCancelar;
        this.pnlPanel3 = pnlPanel3;
        this.pnlPanel2 = pnlPanel2;
        this.pnlPanel4 = pnlPanel4;
        this.pnlPanel1=pnlPanel1;
    }
    

    

    /**
     * Creates new form Panel5
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println("ActionPerformed...");
        if (e.getActionCommand().equals("Aceptar"))
        {
            System.out.println("Clic en el boton para aceptar");
            System.out.println(pnlPanel1.getOption()[0]+ " "+pnlPanel1.getOption()[1]+ " "+pnlPanel1.getOption()[2]+ " ");
            System.out.println(pnlPanel2.getOption()[0]+ " "+pnlPanel2.getOption()[1]+ " "+pnlPanel2.getOption()[2]+ " ");
            System.out.println(pnlPanel3.getNom());
            System.out.println(pnlPanel3.getApe());
            System.out.println(pnlPanel3.getEdad());
            
        }
    else
        { if (e.getActionCommand().equals("Cancelar"))
            pnlPanel1.setDefault();
            pnlPanel2.setDefault();
            pnlPanel3.setDefault();
            pnlPanel4.setDefault();
        }
        
    }

    /**
     * @return the btnAceptar
     */
    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    /**
     * @param btnAceptar the btnAceptar to set
     */
    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    /**
     * @return the btnCancelar
     */
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @param btnCancelar the btnCancelar to set
     */
    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    /**
     * @return the pnlPanel3
     */
    public Panel3 getPnlPanel3() {
        return pnlPanel3;
    }

    /**
     * @param pnlPanel3 the pnlPanel3 to set
     */
    public void setPnlPanel3(Panel3 pnlPanel3) {
        this.pnlPanel3 = pnlPanel3;
    }

    /**
     * @return the pnlPanel2
     */
    public Panel2 getPnlPanel2() {
        return pnlPanel2;
    }

    /**
     * @param pnlPanel2 the pnlPanel2 to set
     */
    public void setPnlPanel2(Panel2 pnlPanel2) {
        this.pnlPanel2 = pnlPanel2;
    }

    /**
     * @return the pnlPanel4
     */
    public Panel4 getPnlPanel4() {
        return pnlPanel4;
    }

    /**
     * @param pnlPanel4 the pnlPanel4 to set
     */
    public void setPnlPanel4(Panel4 pnlPanel4) {
        this.pnlPanel4 = pnlPanel4;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
