/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import javax.swing.border.TitledBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.AbstractBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.JCheckBox;


/* @author jramosal
 */


public class Panel1 extends javax.swing.JPanel {

    private JCheckBox chkA,chkB,chkC;

    /**
     * Creates new form Panel1
     */
    public Panel1(String title) {
        setBorder(new EmptyBorder(0,0,0,0));
        setBorder(new TitledBorder(title));
        
       /* setBorder(new CompoundBorder(new EmptyBorder(0,0,0,0)));*/
        setLayout( null );
        
        chkA=new JCheckBox("Opción A");
        chkA.setBounds(10,18,100,25);
        add(chkA);
        
        chkB=new JCheckBox("Opción B");
        chkB.setBounds(115,18,100,25);
        add(chkB);
        
        chkC=new JCheckBox("Opción C");
        chkC.setBounds(220,18,100,25);
        add(chkC);
        
        initComponents();
        
    }
    
    public void setDefault()
    {
        chkA.setSelected(false);
        chkB.setSelected(false);
        chkB.setSelected(false);
    }
    
    public boolean [] getOption(){
    boolean chk[];
    
    chk = new boolean[3];
    
    chk[0] = chkA.isSelected();
    chk[1] = chkB.isSelected();
    chk[2] = chkC.isSelected();
    return chk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
