/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import javax.swing.JButton;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author jramosal
 */
public class Panel4 extends javax.swing.JPanel {

    private JTextField tf;
    private JComboBox combo;
    private JLabel L_combo;
  
    /**
     * Creates new form Panel4
     */
    public Panel4(String title) {
        setBorder(new EmptyBorder(0,0,0,0));
        setBorder(new TitledBorder(title));
        
            
        L_combo = new JLabel ("Opciones Combo");
        L_combo.setBounds(10,18,100,25);
        add(L_combo);
        
        combo= new JComboBox();
        combo.addItem("Opcion1");
        combo.addItem("Opcion2");
        combo.addItem("Opcion3");
        combo.addItem("Opcion4");  
        combo.setBounds(10,38,100,25);
        add(combo);
        initComponents();
        
    }
    
     public void setDefault()
    {
        combo.setSelectedIndex(1);
     
    }
   /* public String getNom(){
        String nombre = T_nombre.getText();
       return nombre;* //

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
