/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import javax.swing.JRadioButton;
import javax.swing.border.TitledBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.AbstractBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 *
 * @author jramosal
 */
public class Panel3 extends javax.swing.JPanel {
    
    private JTextField T_nombre, T_apellido,T_edad;
    private JLabel L_nombre, L_apellido,L_edad;
    /**
     * Creates new form Panel3
     */
    public Panel3(String title) {
        setBorder(new EmptyBorder(0,0,0,0));
        setBorder(new TitledBorder(title));
        
        L_nombre = new JLabel ("Nombre");
        L_nombre.setBounds(10,18,100,25);
        add(L_nombre);
        
        L_apellido = new JLabel ("Apellido");
        L_apellido.setBounds(110,18,100,25);
        add(L_apellido);
        
        L_edad = new JLabel ("Edad");
        L_edad.setBounds(210,18,100,25);
        add(L_edad);
        initComponents();
        
        T_nombre = new JTextField(15);
        T_nombre.setBounds(10, 40, 100,30);
        add(T_nombre);
        
        T_apellido = new JTextField(15);
        T_apellido.setBounds(110, 40, 100,30);
        add(T_apellido);
        
        T_edad = new JTextField(15);
        T_edad.setBounds(210, 40, 100,30);
        add(T_edad);
    }
    
    public void setDefault()
    {
        T_nombre.setText("");
        T_apellido.setText("");
        T_edad.setText("");
    }
    
    public String getNom(){
        String nombre = T_nombre.getText();
        return nombre;
    }   
    public String getApe(){
        String apellido = T_apellido.getText();
        return apellido;
 }
   
    public String getEdad(){
        String edad = T_edad.getText();
        return edad;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
